CREATE TABLE IF NOT EXISTS `CATEGORIES`
(
  `ID`          BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `NAME`        VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `unique` (`NAME` ASC)
);

CREATE TABLE IF NOT EXISTS `TV_SHOWS`
(
  `ID`          	BIGINT(20)    NOT NULL AUTO_INCREMENT,
  `NAME` 			VARCHAR(256)  NOT NULL,
  `SHORT_DESC` 		VARCHAR(256)  NULL DEFAULT NULL,
  `LONG_DESC` 		VARCHAR(2048) NULL DEFAULT NULL,
  `YEAR` 			YEAR(4) 	  NOT NULL,
  `RECOMMENDED_AGE` TINYINT 	  NOT NULL,
  `CATEGORY_ID` 	BIGINT(20)    NOT NULL,
  `ADVERTISING` 	VARCHAR(256)  NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_TV_SHOWS_CATEGORY_ID`
    FOREIGN KEY (CATEGORY_ID) REFERENCES `CATEGORIES` (ID)
);

CREATE TABLE IF NOT EXISTS `SEASONS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NUMBER` 		TINYINT 	 NOT NULL,
  `NAME` 		VARCHAR(256) NOT NULL,
  `TV_SHOW_ID`  BIGINT(20)   NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_SEASONS_TV_SHOW_ID`
    FOREIGN KEY (TV_SHOW_ID) REFERENCES `TV_SHOWS` (ID)
);

CREATE TABLE IF NOT EXISTS `CHAPTERS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NUMBER` 		TINYINT 	 NOT NULL,
  `NAME` 		VARCHAR(256) NOT NULL,
  `DURATION` 	TINYINT 	 NOT NULL,
  `SEASON_ID`  BIGINT(20)   NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_CHAPTERS_SEASON_ID`
    FOREIGN KEY (SEASON_ID) REFERENCES `SEASONS` (ID)
);
CREATE TABLE IF NOT EXISTS `CATEGORY_TVSHOWS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `TVSHOW_ID`          BIGINT(20)   NOT NULL,
  `CATEGORY_ID`          BIGINT(20)   NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_CATEGORY_TVSHOW_ID`
    FOREIGN KEY (TVSHOW_ID) REFERENCES `TV_SHOWS` (ID),
  CONSTRAINT `FK_TVSHOW_CATEGORY_ID`
    FOREIGN KEY (CATEGORY_ID) REFERENCES `CATEGORIES` (ID)
);
CREATE TABLE IF NOT EXISTS `ACTORS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NAME`          VARCHAR(256)   NOT NULL,
  `YEAR` 			YEAR(4) 	  NOT NULL
);
CREATE TABLE IF NOT EXISTS `ACTORS_TVSHOWS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `TVSHOW_ID`          BIGINT(20)   NOT NULL,
  `ACTOR_ID`          BIGINT(20)   NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_ACTOR_TVSHOW_ID`
    FOREIGN KEY (TVSHOW_ID) REFERENCES `TV_SHOWS` (ID),
  CONSTRAINT `FK_TVSHOW_ACTORS_ID`
    FOREIGN KEY (ACTOR_ID) REFERENCES `TV_SHOWS` (ID)
);

CREATE TABLE IF NOT EXISTS `AWARDS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NAME`      VARCHAR(256)   NOT NULL,
  `YEAR` 			YEAR(4) 	  NOT NULL,
  `tv_show_id` 	BIGINT(20)    NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_AWARDS_tv_show_id`
    FOREIGN KEY (tv_show_id) REFERENCES `TV_SHOWS` (ID)
);